repos:
  - repo: https://github.com/kynan/nbstripout
    rev: 0.6.0
    hooks:
      - id: nbstripout
        args: [
          "--keep-output",
          "--extra-keys",
          "metadata.language_info.version",
          "metadata.kernelspec",
          "metadata.vscode",
        ]
  - repo: https://github.com/mwouts/jupytext
    rev: v1.15.1
    hooks:
    - id: jupytext
      files: "notebooks/sep_analysis_tools/data_loader.ipynb"
      args: [--from, ipynb, --to, ipynb, --sync, --update-metadata, '{"kernelspec": {"display_name": "SEP Analysis", "language": "python", "name": "sep_analysis"}}']
    - id: jupytext
      files: "notebooks/sep_analysis_tools/dynamic_spectrum.ipynb"
      args: [--from, ipynb, --to, ipynb, --sync, --update-metadata, '{"kernelspec": {"display_name": "SEP Analysis", "language": "python", "name": "sep_analysis"}}']
    - id: jupytext
      files: "notebooks/sep_analysis_tools/onset_determination.ipynb"
      args: [--from, ipynb, --to, ipynb, --sync, --update-metadata, '{"kernelspec": {"display_name": "SEP Analysis", "language": "python", "name": "sep_analysis"}}']
    - id: jupytext
      files: "notebooks/sep_analysis_tools/time_shift_analysis.ipynb"
      args: [--from, ipynb, --to, ipynb, --sync, --update-metadata, '{"kernelspec": {"display_name": "SEP Analysis", "language": "python", "name": "sep_analysis"}}']
    - id: jupytext
      files: "notebooks/solarmach/solarmach.ipynb"
      args: [--from, ipynb, --to, ipynb, --sync, --update-metadata, '{"kernelspec": {"display_name": "Solar-MACH", "language": "python", "name": "solarmach"}}']
